spring:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/qxzniot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: admin
      password: admin
    tim:
      url: jdbc:mysql://127.0.0.1:3306/lt3d?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456
      #      driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    host: smtp.qq.com #发送邮件服务器
    username: qxaiot@qq.com #发送邮件的邮箱地址
    password: qvvlfqnkaocqddeb #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    default-encoding: utf-8
    protocol: smtp

#xxl-job
xxl:
  job:
    admin:
      addresses:
    executor:
      appname: lito-job
      ip:
      port: 9995
      logpath: /logs/lito-job
      logretentiondays: 10
    accessToken: